name: build_website

# Only run this workflow, when it is pushed to masters
#on:
#  push:
#    branches:
#      - master

on:
  push:
    branches:
     - main
    tags-ignore:
      - '**'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    # download wheel that was build and uploaded in the build step
#    - uses: actions/download-artifact@v1
#      with:
#        name: distributions
#        path: dist

    - name: Install development and distributions version
      run: |
        pip install --upgrade pip
        pip install .[doc]
        pip install pypandoc_binary

    - name: Setup pandoc
#      uses: r-lib/actions/setup-pandoc@v1
#      with:
#        pandoc-version: '4.0.0' # The pandoc version to download (if necessary) and use
      uses: siacodelabs/setup-pandoc@v1
      with:
        xelatex: true.

    # didn't need to change anything here, but had to add sphinx.ext.githubpages
    # to my conf.py extensions list. that fixes the broken uploads
    - name: Building documentation
      run: |
        sphinx-apidoc -a -o ./doc/pyapi/ ./src/grid ./src/grid/tests/ ./src/grid/test/ ./src/grid/data/ --separate
        sphinx-build -M html doc _build 

    # still need to build and set the PAT to get a rebuild on the pages job,
    # apart from that quite clean and nice
    - name: github pages deploy
      uses: peaceiris/actions-gh-pages@v2.3.1
      env:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: _build/html

    # since gh-pages has a history, this step might no longer be necessary.
#    - uses: actions/upload-artifact@v1
#      with:
#        name: documentation
#        path: public
